from book import Book

book1 = Book("1984", "George Orwell", True, "Fiction")
book2 = Book("To Kill a Mockingbird", "Harper Lee", False, "Fiction")
print(f"Title: {book1.title}, Author: {book1.author}, Available: {book1.available}, Genre: {book1.genre}")
print(f"Title: {book2.title}, Author: {book2.author}, Available: {book2.available}, Genre: {book2.genre}")
book1.borrow()
book2.borrow()
book1.return_book()
book2.return_book()
book1.display_info()
book2.display_info()
print(f"Library Name before changing it for the 1st book: {Book.library_name}")
book1.change_library_name("Downtown Library")
print(f"Library Name after the change: {book1.library_name}")
Book.is_valid_title("The Great Gatsby")
Book.is_valid_title("")
Book.show_count()
book= Book.from_string("Clean Code, Robert C. Martin, True, Fiction")
book.display_info()